language: java
jdk:
  - oraclejdk11

notifications:
  slack:
    rooms:
      - pictopage:GgJNEnLcl4annmdzEwdCVbqY#random

#TODO: Get cobertura plugin for Gradle to run this.
#script: "./gradlew install"

after_success:
  - bash <(curl -s https://codecov.io/bash)
