FROM adoptopenjdk/openjdk11:x86_64-alpine-jre-11.0.4_11 AS activiti-demo
MAINTAINER 'Artemas Muzanenhamo'
# copy JAR into image
COPY build/libs/Activiti-Demo-*-SNAPSHOT.jar /activiti-demo.jar
# expose port
EXPOSE 8080
# run application with this command line
CMD ["java", "-jar", "/activiti-demo.jar"]