spring:
  profiles:
    active:
    - development
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:activiti-demo;MODE=MySQL

---

spring:
  profiles:
    active:
    - playground
    jpa:
        database: MYSQL
        hibernate:
            ddl-auto: validate

    datasource:
        url: jdbc:mysql://localhost:3306/activiti-demo
        username: root
        password: password
        driver-class-name: com.mysql.jdbc.Driver
